# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :all_tests do
    scan(
      workspace: "Listen anonymously.xcodeproj/project.xcworkspace",
      scheme: "Listen anonymously Ext Tests",
      testplan: "Listen anonymously Test Plan",
      destination: "platform=iOS Simulator,name=CI-iPhone",
      parallel_testing: true,
      code_coverage: true,
      clean: true,
      result_bundle: true,
      output_directory: "./fastlane/test_output"
    )
  end
end


lane :lint do
  Dir.chdir("..") do
    sh "swiftlint lint --strict"
  end
end
